### ISSUE TITLE
Better Image training?

### ISSUE THREAD

**Issue by ephoras** [abhisuri97/auto-alt-text-lambda-api#1]
First, i wanted to tell you how much i like the idea of your API / Chrome extension.
It would be a great addition to one of the projects i am currently working on, but sadly the image recognition is way of base most of the times.
We are mostly working with historical pictures and i guess thats part of the Problem. The Neural Network seems to be trained on "modern" Pictures, like Holiday snapshots and so on.
Is there a way to (re-)train the AI to work better with our picture base? We have somewhere between 3000 and 7000 Pictures :)
Thanks in advance

**Comment by abhisuri97** [comment]
hey ephoras, I'd recommend that you take a look at the original im2txt github repo https://github.com/tensorflow/models/tree/master/im2txt 
The historical images are definitely not in the dataset of MSCOCO, but I think if you train from scratch, you can see some improvement. My only concern is that the picture set may be slightly on the smaller side (perhaps if you apply some artificial transforms such as rotation, warping, and scaling, you can generate much more data). After you get your trained model, you can easily plug it into this repo.
